title: Morceau

columns:
  - width: 2/3      
    fields:
      artist:
        type: text
        label: Artiste/groupe
        width: 3/4
      publisher:
        type: select
        width: 1/4
        options:
          - v
          - jm
          - j
      audio:
        type: files
        label: MP3
        multiple: false
        width: 1/2
      youtube:
        type: url
        label: YT
        width: 1/2
      text:
        label: Text
        type: markdown
      
  - width: 1/3
    sections:
      files:
        type: files
        headline: Fichiers


     

addFields:
  title:
    type: text
    label: Titre
  artist:
    type: text
    label: Artiste        